import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Vagabond Studios - Projects",
	description: "Generated by create next app",
};

export default function ProjectsLayout({
	children,
}: {
	children: React.ReactNode;
 }) {
	return (
		<div >
			{children}
		</div>
	);
}