import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/Components/Header";
import Nav from "@/Components/Nav";
import Footer from "@/Components/Footer";

const generalSans = localFont({src: '../../public/fonts/GeneralSans-Regular.otf'});

export const metadata: Metadata = {
	title: "Vagabond Studios",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={generalSans.className}>
				<Nav />
				<Header />
				{children}
				<Footer/>
			</body>
		</html>
	);
}
