import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Nav from "@/Components/Nav"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vagabond Studios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <Header />
        {children}
      </body>
    </html>
  );
}
